name: testing_exp_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  provider: ^6.0.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  community_charts_flutter: ^1.0.0
  timezone: ^0.9.2
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^15.1.0
  syncfusion_flutter_charts: ^29.1.35
  cupertino_icons: ^1.0.8
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

